#!/usr/bin/env python2
# FILE			: constant.py
# AUTHOR		: K.Supasan
# CREATE ON		: 2019, July 10 (UTC+0)
# MAINTAINER	: K.Supasan

# README

# REFERENCE

_COMMAND_PRINT_ALL_ = False
_COMMAND_PRINT_CHECK_ = True
_COMMAND_PRINT_ORDER_ = False
_COMMAND_PRINT_ECHO_ = True
_COMMAND_PRINT_FORCE_ = True

if( _COMMAND_PRINT_ALL_ ):
    _COMMAND_PRINT_CHECK_ = True
    _COMMAND_PRINT_ORDER_ = True
    _COMMAND_PRINT_ECHO_ = True
    _COMMAND_PRINT_FORCE_ = True
